package com.siakad.enums;

public enum RoleType {
    FINANCE_ADMIN_UNIVERSITY,
    FINANCE_ADMIN_FACULTY,
    FINANCE_ADMIN_PROGRAM,
    ACADEMIC_ADMIN_UNIVERSITY,
    ACADEMIC_ADMIN_FACULTY,
    ACADEMIC_ADMIN_PROGRAM,
    STUDENT,
    LECTURER
}
