-- SIAK MAHASISWA TABLE --
CREATE TABLE IF NOT EXISTS public.siak_mahasiswa (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    siak_user_id UUID NOT NULL,
    siak_program_studi_id UUID NOT NULL,
    nama VARCHAR(255) NOT NULL,
    npm VARCHAR(12) NOT NULL,
    jenis_kelamin VARCHAR(12) NOT NULL,
    tempat_lahir VARCHAR(40) NOT NULL,
    tanggal_lahir DATE NOT NULL,
    nik VARCHAR(16) NOT NULL,
    no_kk VARCHAR(16) NOT NULL,
    periode_masuk VARCHAR(45) NOT NULL,
    sistem_kuliah VARCHAR(20) NOT NULL,
    kelas VARCHAR(20) NOT NULL,
    jenis_pendaftaran VARCHAR(15) NOT NULL,
    jalur_pendaftaran VARCHAR(15),
    gelombang VARCHAR(20) NOT NULL,
    tanggal_masuk DATE NOT NULL,
    kebutuhan_khusus BOOLEAN,
    status_mahasiswa VARCHAR(20) NOT NULL,
    alamat_ktp TEXT  NOT NULL,
    rt_ktp INT NOT NULL,
    rw_ktp INT NOT NULL,
    desa_ktp VARCHAR(100) NOT NULL,
    provinsi_ktp VARCHAR(100) NOT NULL,
    kode_pos_ktp VARCHAR(5) NOT NULL,
    status_tinggal_ktp VARCHAR(20) NOT NULL,
    alamat_domisili TEXT NOT NULL,
    rt_domisili INT NOT NULL,
    rw_domisili INT NOT NULL,
    desa_domisili VARCHAR(100) NOT NULL,
    provinsi_domisili VARCHAR(100) NOT NULL,
    kode_pos_domisili VARCHAR(5) NOT NULL,
    status_tinggal_domisili VARCHAR(20) NOT NULL,
    no_telepon VARCHAR(15) NOT NULL,
    no_hp VARCHAR(15) NOT NULL,
    email_pribadi VARCHAR(255) NOT NULL,
    email_kampus VARCHAR(255) NOT NULL,
    no_terdaftar VARCHAR(20) NOT NULL,
    pendidikan_asal VARCHAR(100) NOT NULL,
    provinsi_sekolah VARCHAR(100) NOT NULL,
    kota_kab_sekolah VARCHAR(100) NOT NULL,
    nama_pendidikan_asal VARCHAR(255) NOT NULL,
    alamat_sekolah TEXT  NOT NULL,
    telepon_sekolah VARCHAR(15) NOT NULL,
    no_ijazah_sekolah VARCHAR(25) NOT NULL,
    semester INT NOT NULL,
    ijazah_sekolah BYTEA,
    foto_profil BYTEA,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (siak_user_id) REFERENCES siak_user(id),
    FOREIGN KEY (siak_program_studi_id) REFERENCES siak_program_studi(id)
);

CREATE INDEX IF NOT EXISTS idx_mahasiswa_user_id ON public.siak_mahasiswa(siak_user_id);
